# Generated by Django 4.2.4 on 2023-11-05 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('nota', models.IntegerField()),
                ('respostas', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(db_column='vaga_id', on_delete=django.db.models.deletion.CASCADE, to='geo.vagas')),
            ],
        ),
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.avaliacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FiltroAcessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.acessibilidade')),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.filtro')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_avaliacoes', models.PositiveIntegerField(default=0)),
                ('media_notas', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('vaga', models.ForeignKey(db_column='vaga_id', on_delete=django.db.models.deletion.CASCADE, to='geo.vagas')),
            ],
        ),
        migrations.CreateModel(
            name='AvaliacaoAcessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessibilidade_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.acessibilidade')),
                ('avaliacao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.avaliacao')),
            ],
        ),
        migrations.CreateModel(
            name='VagaAcessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.acessibilidade')),
                ('vaga', models.ForeignKey(db_column='vaga_id', on_delete=django.db.models.deletion.CASCADE, to='geo.vagas')),
            ],
            options={
                'unique_together': {('vaga', 'acessibilidade')},
            },
        ),
    ]
