# Generated by Django 4.2.4 on 2023-11-11 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filtro',
            name='nome',
            field=models.TextField(),
        ),
    ]
