# Generated by Django 4.2.4 on 2023-10-19 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('avaliacao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='avaliacao',
            name='respostas',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.avaliacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FiltroAcessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.acessibilidade')),
                ('filtro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.filtro')),
            ],
        ),
        migrations.CreateModel(
            name='VagaAcessibilidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acessibilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='avaliacao.acessibilidade')),
                ('vaga', models.ForeignKey(db_column='vaga_id', on_delete=django.db.models.deletion.CASCADE, to='geo.vagas')),
            ],
            options={
                'unique_together': {('vaga', 'acessibilidade')},
            },
        ),
    ]
