# Generated by Django 4.2.4 on 2023-11-05 21:38

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('index', models.BigIntegerField(blank=True, db_column='index', primary_key=True, serialize=False, unique=True)),
                ('numerovaga', models.BigIntegerField(blank=True, db_column='NumeroVaga', null=True)),
                ('local', models.TextField(blank=True, db_column='Local', null=True)),
                ('complemento', models.TextField(blank=True, db_column='Complemento', null=True)),
                ('quantidadev', models.BigIntegerField(blank=True, db_column='QuantidadeV', null=True)),
                ('numeroarea', models.BigIntegerField(blank=True, db_column='NumeroArea', null=True)),
                ('area', models.TextField(blank=True, db_column='Area', null=True)),
                ('tipo', models.TextField(blank=True, db_column='Tipo', null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('total_avaliacoes', models.PositiveIntegerField(default=0)),
                ('media_notas', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('acess', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, size=None)),
            ],
            options={
                'db_table': 'Vagas',
                'managed': True,
            },
        ),
    ]
