# Generated by Django 4.2.4 on 2023-10-15 19:01

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vagas',
            fields=[
                ('index', models.BigIntegerField(blank=True, db_column='index', primary_key=True, serialize=False, unique=True)),
                ('numerovaga', models.BigIntegerField(blank=True, db_column='NumeroVaga', null=True)),
                ('local', models.TextField(blank=True, db_column='Local', null=True)),
                ('complemento', models.TextField(blank=True, db_column='Complemento', null=True)),
                ('quantidadev', models.BigIntegerField(blank=True, db_column='QuantidadeV', null=True)),
                ('numeroarea', models.BigIntegerField(blank=True, db_column='NumeroArea', null=True)),
                ('area', models.TextField(blank=True, db_column='Area', null=True)),
                ('tipo', models.TextField(blank=True, db_column='Tipo', null=True)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
            options={
                'db_table': 'Vagas',
                'managed': False,
            },
        ),
    ]
